services:
  backend-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: news_portal_user
      POSTGRES_PASSWORD: d123
      POSTGRES_DB: news_portal
    volumes:
      - backend-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news_portal_user -d news_portal"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://news_portal_user:d123@backend-db:5432/news_portal?schema=public
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - backend-db
    command: >
      sh -c "
      until pg_isready -h backend-db -U news_portal_user -d news_portal; do
        echo 'Waiting for Postgres...'; sleep 2;
      done;
      npx prisma migrate deploy &&
      node src/server.js
      "

volumes:
  backend-postgres-data:
